services:
  # This service is for fast, standard Python development
  local-dev:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app  # "Hot-reloading": changes in your code reflect instantly
    env_file:
      - .env  # This tells Docker to load your .env file
    ports:
      - "5000:5000"
    environment:
      - ENV=development
  
  ngrok:
      image: ngrok/ngrok:latest
      command:
        - "http"
        - "local-dev:8000" # It points to the service name, not localhost!
      environment:
        - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
        - NGROK_LOG=stdout
      ports:
        - "4040:4040"
      depends_on:
        - local-dev

  # This service mimics the actual AWS Lambda environment
  lambda-test:
    build:
      context: .
      dockerfile: Dockerfile.aws
    ports:
      - "9000:8080"
    environment:
      - ENV=production