# Use a standard Python image
FROM python:3.11-slim

# Set a standard working directory
WORKDIR /app

# Copy and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your code
COPY . .

# Run your script normally
CMD ["python", "app.py"]